### ISSUE TITLE
migrate with custom config file does not generate file with similar name

### ISSUE THREAD

**Issue by flip111** [purescript/spago-legacy#2]
```shell
spago -x spago.example.dhall migrate
[info] Writing the new config format to spago.yaml...
```

Expected it would write `spago.example.yaml`

**Comment by JordanMartinez** [comment]
I don't understand the issue here. `spago.example.yaml` AFAIU wouldn't work in the new spago as the file must be named `spago.yaml`.

Why do you expect it to be named that?

**Comment by flip111** [comment]
I forgot about that :/

Shouldn't the new spago also have a flag for a custom .yaml file?

**Comment by natefaubion** [comment]
I think the goal is that you don't have separate spago.yaml files for each target, you have different targets in the one spago.yaml.

**Comment by flip111** [comment]
Let's close this for now until at least spago@next has support for something like this.

**Comment by f-f** [comment]
spago-next won't support this - in the new world your config files are always called `spago.yaml`, and the basic unit is "the package", which at minimum is just a folder with said config inside.

So instead of having a `spago.example.dhall` and calling `spago -x spago.example.dhall` you'll have a `example/spago.yaml` and call `spago -p example`
